version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d # Monta scripts de inicialização
    networks:
      - blanktask-network
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_web
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - blanktask-network
    env_file:
      - .env

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
     APP_PORT: ${APP_PORT}
     POSTGRES_HOST: ${POSTGRES_HOST}
     DB_PORT:   ${DB_PORT}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB:   ${POSTGRES_DB}
    networks:
      - blanktask-network
    env_file:
      - .env

networks:
  blanktask-network:
    driver: bridge

volumes:
  db_data:
  pgadmin_data: